version: '3.7'

services:
  aurora-db:
    image: postgres:12
    container_name: aurora-db
    environment:
      POSTGRES_USER: aurora
      POSTGRES_PASSWORD: aurora
      POSTGRES_DB: aurora
    ports:
      - "5432:5432"
  memory-db:
    image: redis:6
    container_name: memory-db
    ports:
      - "6379:6379"